name: Build and Publish CLI

on:
  release:
    types: [published]

concurrency:
  group: publish-cli-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'arm64_runner' || 'ubuntu-latest' }}
    if: github.repository == 'langgenius/dify-plugin-daemon'
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            target: linux-amd64
          - platform: linux/arm64
            target: linux-arm64
          - platform: linux/amd64
            target: darwin-amd64
          - platform: linux/arm64
            target: darwin-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Transform platform
        run: |
          GOOS=$(echo "${{ matrix.target }}" | cut -d '-' -f 1)
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          GOARCH=$(echo "${{ matrix.target }}" | cut -d '-' -f 2)
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Build CLI
        run: |
          go mod tidy
          GOOS=${{ env.GOOS }} GOARCH=${{ env.GOARCH }} go build -o dify-plugin-${{ env.GOOS }}-${{ env.GOARCH }} ./cmd/commandline

      - name: Publish CLI
        run: |
          gh release upload ${{ github.event.release.tag_name }} dify-plugin-${{ env.GOOS }}-${{ env.GOARCH }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
