name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-amd64-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Golang 1.20
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Setup License
        run: go run cmd/license/generate/main.go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
